# Generated by Django 3.0.4 on 2020-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200317_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='imazhi',
            field=models.ImageField(default='cat_images/default.jpg', upload_to='cat_images'),
        ),
    ]
