# Generated by Django 3.0.4 on 2020-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200404_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasa',
            name='chat',
            field=models.CharField(default='Nuk ka dhome chat.', max_length=700),
        ),
    ]
