# Generated by Django 3.0.4 on 2020-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200404_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendet',
            name='chat',
        ),
        migrations.AddField(
            model_name='klasa',
            name='chat',
            field=models.CharField(default='Nuk ka dhome chat.', max_length=700),
        ),
    ]
