# Generated by Django 3.0.4 on 2020-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200404_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasa',
            name='chat',
            field=models.TextField(default='Nuk ka dhome chat.', max_length=700),
        ),
    ]
